### ISSUE TITLE
Static Docker client binary

### ISSUE THREAD

**Issue by whatever4711** [hypriot/rpi-consul-template#2]
It would be great to integrate the static binary of [Docker](https://master.dockerproject.org/linux/arm/docker) to restart docker-services, when changes are detected.

However, the current static build provides a newer API version than Hypriot's docker build: 

```
Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   8038e32
 Built:        Thu Feb  4 19:36:59 2016
 OS/Arch:      linux/arm
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
```

**Comment by MathiasRenner** [comment]
@whatever4711 Andreas and me just tested this - if the host's binary is latest, it works fine:

```
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   46eb470
 Built:        Wed Jan 13 12:36:53 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   590d5108
 Built:        Thu Feb  4 20:37:07 2016
 OS/Arch:      linux/arm
```

Thus, you need to update the host's Docker version. If you update it, the error is gone: 

```
sudo apt-get update && sudo apt-get upgrade
```

... since Docker 1.10.1 is in Hypriot's deb repository.
